### ISSUE TITLE
XML Output Issues

### ISSUE THREAD

**Issue by ForbiddenEra** [MoLow/reporters#42]
See https://github.com/nodejs/tap2junit/issues/50#issuecomment-1493229220 for more details potentially.

I've been mostly running my tests with a `run_tests.js` that `import`s all the tests files and runs the exported default function which contains the tests, eg:

`run-tests.js`:
```javascript
import testSuite1 from './test/testSuite1.js';
import testSuite2 from './test/testSuite2.js';
import testSuite3 from './test/testSuite3.js';
import testSuite4 from './test/testSuite4.js';

(async()=>{
	await testSuite1();
	await testSuite2();
	await testSuite3();
	await testSuite4();
})();
```

Each test suite file has either one suite with some sub-suites, eg:

```javascript
import test from 'node:test';
import assert from 'node:assert/strict';
export default async() => {
    t.test('Test Suite #3', async(t) => {
        await t.test('Test #1', async(tt) => {});
        await t.test('Test #2', async(tt) => {});
    });
};
```
Or a test suite with sub-grouped test suites, eg:
```javascript
import test from 'node:test';
import assert from 'node:assert/strict';
export default async() => {
    test('Test Suite #2', async(t) => {
        await t.test('Test Group #1', async(t) => {
            await t.test('Test #1', async(tt) => {});
            await t.test('Test #2', async(tt) => {});
        });
        await t.test('Test Group #2', async(t) => {
            await t.test('Test #1', async(tt) => {});
            await t.test('Test #2', async(tt) => {});
        });
    });
};
```
Or, just multiple suites:
```javascript
import test from 'node:test';
import assert from 'node:assert/strict';
export default async() => {
    t.test('Test Suite #1b', async(t) => {
        await t.test('Test #1', async(tt) => {});
        await t.test('Test #2', async(tt) => {});
    });
    t.test('Test Suite #1a', async(t) => {
        await t.test('Test #1', async(tt) => {});
        await t.test('Test #2', async(tt) => {});
    });
};
```

While this results in `TAP` output that looks correct, the reporter gives me this:
```xml
<testsuites>
        <testsuite name="Test Suite #1b" time="0.002864" disabled="0" errors="0" tests="2" failures="0" skipped="0">
                <testcase name="Test #1" time="0.000700" classname="test"/>
                <testcase name="Test #2" time="0.000133" classname="test"/>
        <testsuite name="Test Suite #1a" time="0.000877" disabled="0" errors="0" tests="2" failures="0" skipped="0">
                <testcase name="Test #1" time="0.000165" classname="test"/>
                <testcase name="Test #2" time="0.000407" classname="test"/>
        </testsuite>
        <testsuite name="Test Suite #2" time="0.002103" disabled="0" errors="0" tests="2" failures="0" skipped="0">
                <testsuite name="Test Group #1" time="0.000851" disabled="0" errors="0" tests="2" failures="0" skipped="0">
                        <testcase name="Test #1" time="0.000214" classname="test"/>
                        <testcase name="Test #2" time="0.000153" classname="test"/>
                </testsuite>
                <testsuite name="Test Group #2" time="0.000667" disabled="0" errors="0" tests="2" failures="0" skipped="0">
                        <testcase name="Test #1" time="0.000159" classname="test"/>
                        <testcase name="Test #2" time="0.000106" classname="test"/>
                </testsuite>
        </testsuite>
        <testsuite name="Test Suite #3" time="0.000877" disabled="0" errors="0" tests="2" failures="0" skipped="0">
                <testcase name="Test Suite #3/Test #1" time="0.000145" classname="test"/>
                <testcase name="Test Suite #3/Test #2" time="0.000276" classname="test"/>
        </testsuite>
        <testsuite name="Test Suite #4" time="0.000740" disabled="0" errors="0" tests="2" failures="0" skipped="0">
                <testcase name="Test #1" time="0.000125" classname="test"/>
                <testcase name="Test #2" time="0.000146" classname="test"/>
        </testsuite>
        </testsuite>
</testsuites>
```

It seems that whichever suite comes first ends up wrapping any other suites, here's the TAP output from the same run:

```yaml
TAP version 13
# Subtest: Test Suite \#1b
    # Subtest: Test \#1
    ok 1 - Test \#1
      ---
      duration_ms: 0.4764
      ...
    # Subtest: Test \#2
    ok 2 - Test \#2
      ---
      duration_ms: 0.0968
      ...
    1..2
ok 1 - Test Suite \#1b
  ---
  duration_ms: 1.9371
  ...
# Subtest: Test Suite \#1a
    # Subtest: Test \#1
    ok 1 - Test \#1
      ---
      duration_ms: 0.122
      ...
    # Subtest: Test \#2
    ok 2 - Test \#2
      ---
      duration_ms: 0.1004
      ...
    1..2
ok 2 - Test Suite \#1a
  ---
  duration_ms: 0.5766
  ...
# Subtest: Test Suite \#2
    # Subtest: Test Group \#1
        # Subtest: Test \#1
        ok 1 - Test \#1
          ---
          duration_ms: 1.446
          ...
        # Subtest: Test \#2
        ok 2 - Test \#2
          ---
          duration_ms: 0.135
          ...
        1..2
    ok 1 - Test Group \#1
      ---
      duration_ms: 1.932
      ...
    # Subtest: Test Group \#2
        # Subtest: Test \#1
        ok 1 - Test \#1
          ---
          duration_ms: 0.1035
          ...
        # Subtest: Test \#2
        ok 2 - Test \#2
          ---
          duration_ms: 0.0718
          ...
        1..2
    ok 2 - Test Group \#2
      ---
      duration_ms: 0.4181
      ...
    1..2
ok 3 - Test Suite \#2
  ---
  duration_ms: 2.6649
  ...
# Subtest: Test Suite \#3
    # Subtest: Test Suite \#3/Test \#1
    ok 1 - Test Suite \#3/Test \#1
      ---
      duration_ms: 0.0922
      ...
    # Subtest: Test Suite \#3/Test \#2
    ok 2 - Test Suite \#3/Test \#2
      ---
      duration_ms: 0.2016
      ...
    1..2
ok 4 - Test Suite \#3
  ---
  duration_ms: 0.6171
  ...
# Subtest: Test Suite \#4
    # Subtest: Test \#1
    ok 1 - Test \#1
      ---
      duration_ms: 0.1008
      ...
    # Subtest: Test \#2
    ok 2 - Test \#2
      ---
      duration_ms: 0.0929
      ...
    1..2
ok 5 - Test Suite \#4
  ---
  duration_ms: 0.4917
  ...
1..5
# tests 5
# pass 5
# fail 0
# cancelled 0
# skipped 0
# todo 0
# duration_ms 29.6044
```

Now, I understand this isn't really the "normal" or perhaps "ideal" way to run tests. I had reasons for this, those reasons will become moot due to committed fixes already made to `node`, not sure when they'll drop but..

If I do it the "normal" way and completely forget about `run_tests.js` and take each suite out of the `export` so that it's just in the top level, eg:

```javascript
import test from 'node:test';
import assert from 'node:assert/strict';

t.test('Test Suite #3', async(t) => {
    await t.test('Test #1', async(tt) => {});
    await t.test('Test #2', async(tt) => {});
});
```

And have my tests in `test/*` as the docs suggest and run the tests with `node --test` - I get a similar but not quite the same result:

```xml
<testsuites>
        <testsuite name="Test Suite #4" time="0.003108" disabled="0" errors="0" tests="2" failures="0" skipped="0">
                <testcase name="Test #1" time="0.000764" classname="test"/>
                <testcase name="Test #2" time="0.000118" classname="test"/>
        <testsuite name="Test Suite #1b" time="0.003074" disabled="0" errors="0" tests="2" failures="0" skipped="0">
                <testcase name="Test #1" time="0.000924" classname="test"/>
                <testcase name="Test #2" time="0.000144" classname="test"/>
        </testsuite>
        <testsuite name="Test Suite #1a" time="0.000617" disabled="0" errors="0" tests="2" failures="0" skipped="0">
                <testcase name="Test #1" time="0.000179" classname="test"/>
                <testcase name="Test #2" time="0.000124" classname="test"/>
        </testsuite>
        <testsuite name="Test Suite #2" time="0.004215" disabled="0" errors="0" tests="2" failures="0" skipped="0">
                <testsuite name="Test Group #1" time="0.002065" disabled="0" errors="0" tests="2" failures="0" skipped="0">
                        <testcase name="Test #1" time="0.000751" classname="test"/>
                        <testcase name="Test #2" time="0.000129" classname="test"/>
                </testsuite>
                <testsuite name="Test Group #2" time="0.000813" disabled="0" errors="0" tests="2" failures="0" skipped="0">
                        <testcase name="Test #1" time="0.000166" classname="test"/>
                        <testcase name="Test #2" time="0.000132" classname="test"/>
                </testsuite>
        </testsuite>
        <testsuite name="Test Suite #3" time="0.002005" disabled="0" errors="0" tests="2" failures="0" skipped="0">
                <testcase name="Test Suite #3/Test #1" time="0.000444" classname="test"/>
                <testcase name="Test Suite #3/Test #2" time="0.000099" classname="test"/>
        </testsuite>
        </testsuite>
</testsuites>
```

Again, it's as if whichever test appears first ends up becoming the root test with all other tests wrapped by it. From what I can tell by reading the docs for `node:test`, there shouldn't really be a much more standard way to run the tests and again the `TAP` output is as expected:

```yaml
TAP version 13
# Subtest: Test Suite \#4
    # Subtest: Test \#1
    ok 1 - Test \#1
      ---
      duration_ms: 0.677
      ...
    # Subtest: Test \#2
    ok 2 - Test \#2
      ---
      duration_ms: 0.1329
      ...
    1..2
ok 1 - Test Suite \#4
  ---
  duration_ms: 3.0094
  ...
# Subtest: Test Suite \#1b
    # Subtest: Test \#1
    ok 1 - Test \#1
      ---
      duration_ms: 0.923
      ...
    # Subtest: Test \#2
    ok 2 - Test \#2
      ---
      duration_ms: 0.161
      ...
    1..2
ok 2 - Test Suite \#1b
  ---
  duration_ms: 3.1304
  ...
# Subtest: Test Suite \#1a
    # Subtest: Test \#1
    ok 1 - Test \#1
      ---
      duration_ms: 0.2893
      ...
    # Subtest: Test \#2
    ok 2 - Test \#2
      ---
      duration_ms: 0.1412
      ...
    1..2
ok 3 - Test Suite \#1a
  ---
  duration_ms: 0.7703
  ...
# Subtest: Test Suite \#2
    # Subtest: Test Group \#1
        # Subtest: Test \#1
        ok 1 - Test \#1
          ---
          duration_ms: 0.6774
          ...
        # Subtest: Test \#2
        ok 2 - Test \#2
          ---
          duration_ms: 0.151
          ...
        1..2
    ok 1 - Test Group \#1
      ---
      duration_ms: 1.9833
      ...
    # Subtest: Test Group \#2
        # Subtest: Test \#1
        ok 1 - Test \#1
          ---
          duration_ms: 1.5448
          ...
        # Subtest: Test \#2
        ok 2 - Test \#2
          ---
          duration_ms: 0.2315
          ...
        1..2
    ok 2 - Test Group \#2
      ---
      duration_ms: 2.2979
      ...
    1..2
ok 3 - Test Suite \#2
  ---
  duration_ms: 5.7153
  ...
# Subtest: Test Suite \#3
    # Subtest: Test Suite \#3/Test \#1
    ok 1 - Test Suite \#3/Test \#1
      ---
      duration_ms: 0.639
      ...
    # Subtest: Test Suite \#3/Test \#2
    ok 2 - Test Suite \#3/Test \#2
      ---
      duration_ms: 0.1275
      ...
    1..2
ok 4 - Test Suite \#3
  ---
  duration_ms: 2.9442
  ...
1..5
# tests 5
# pass 5
# fail 0
# cancelled 0
# skipped 0
# todo 0
# duration_ms 1176.6842
```

If I go back to using my `run-tests.js` to initiate the tests and wrap each exported function from each suite in it's own test, eg.

```javascript
import test from 'node:test';

import testSuite1 from './test/testSuite1.js';
import testSuite2 from './test/testSuite2.js';
import testSuite3 from './test/testSuite3.js';
import testSuite4 from './test/testSuite4.js';

(async()=>{
    test('All Tests', async(t) => {
	await testSuite1(t);
	await testSuite2(t);
	await testSuite3(t);
	await testSuite4(t);
    });
})();
```

And, of course, update each suite file to use the provided `t`:
```javascript
export default async(t) => {
    await t.test('Test Suite #4', async(t) => {
        await t.test('Test #1', async(tt) => {});
        await t.test('Test #2', async(tt) => {});
    });
};
```

I get a more reasonable seeming output:

```xml
<testsuites>
        <testsuite name="All Tests" time="0.008034" disabled="0" errors="0" tests="5" failures="0" skipped="0">
                <testsuite name="Test Suite #1b" time="0.001705" disabled="0" errors="0" tests="2" failures="0" skipped="0">
                        <testcase name="Test #1" time="0.000463" classname="test"/>
                        <testcase name="Test #2" time="0.000128" classname="test"/>
                </testsuite>
                <testsuite name="Test Suite #1a" time="0.000767" disabled="0" errors="0" tests="2" failures="0" skipped="0">
                        <testcase name="Test #1" time="0.000163" classname="test"/>
                        <testcase name="Test #2" time="0.000130" classname="test"/>
                </testsuite>
                <testsuite name="Test Suite #2" time="0.002277" disabled="0" errors="0" tests="2" failures="0" skipped="0">
                        <testsuite name="Test Group #1" time="0.000794" disabled="0" errors="0" tests="2" failures="0" skipped="0">
                                <testcase name="Test #1" time="0.000367" classname="test"/>
                                <testcase name="Test #2" time="0.000135" classname="test"/>
                        </testsuite>
                        <testsuite name="Test Group #2" time="0.001077" disabled="0" errors="0" tests="2" failures="0" skipped="0">
                                <testcase name="Test #1" time="0.000189" classname="test"/>
                                <testcase name="Test #2" time="0.000276" classname="test"/>
                        </testsuite>
                </testsuite>
                <testsuite name="Test Suite #3" time="0.000778" disabled="0" errors="0" tests="2" failures="0" skipped="0">
                        <testcase name="Test Suite #3/Test #1" time="0.000390" classname="test"/>
                        <testcase name="Test Suite #3/Test #2" time="0.000150" classname="test"/>
                </testsuite>
                <testsuite name="Test Suite #4" time="0.000864" disabled="0" errors="0" tests="2" failures="0" skipped="0">
                        <testcase name="Test #1" time="0.000318" classname="test"/>
                        <testcase name="Test #2" time="0.000140" classname="test"/>
                </testsuite>
        </testsuite>
</testsuites>
```

And the `TAP` output for that run:

```yaml
TAP version 13
# Subtest: All Tests
    # Subtest: Test Suite \#1b
        # Subtest: Test \#1
        ok 1 - Test \#1
          ---
          duration_ms: 0.6373
          ...
        # Subtest: Test \#2
        ok 2 - Test \#2
          ---
          duration_ms: 0.1427
          ...
        1..2
    ok 1 - Test Suite \#1b
      ---
      duration_ms: 1.9678
      ...
    # Subtest: Test Suite \#1a
        # Subtest: Test \#1
        ok 1 - Test \#1
          ---
          duration_ms: 0.1837
          ...
        # Subtest: Test \#2
        ok 2 - Test \#2
          ---
          duration_ms: 0.1304
          ...
        1..2
    ok 2 - Test Suite \#1a
      ---
      duration_ms: 0.8122
      ...
    # Subtest: Test Suite \#2
        # Subtest: Test Group \#1
            # Subtest: Test \#1
            ok 1 - Test \#1
              ---
              duration_ms: 0.4172
              ...
            # Subtest: Test \#2
            ok 2 - Test \#2
              ---
              duration_ms: 0.1333
              ...
            1..2
        ok 1 - Test Group \#1
          ---
          duration_ms: 0.867
          ...
        # Subtest: Test Group \#2
            # Subtest: Test \#1
            ok 1 - Test \#1
              ---
              duration_ms: 0.2219
              ...
            # Subtest: Test \#2
            ok 2 - Test \#2
              ---
              duration_ms: 0.2909
              ...
            1..2
        ok 2 - Test Group \#2
          ---
          duration_ms: 1.1123
          ...
        1..2
    ok 3 - Test Suite \#2
      ---
      duration_ms: 2.5096
      ...
    # Subtest: Test Suite \#3
        # Subtest: Test Suite \#3/Test \#1
        ok 1 - Test Suite \#3/Test \#1
          ---
          duration_ms: 0.3034
          ...
        # Subtest: Test Suite \#3/Test \#2
        ok 2 - Test Suite \#3/Test \#2
          ---
          duration_ms: 0.1237
          ...
        1..2
    ok 4 - Test Suite \#3
      ---
      duration_ms: 0.6469
      ...
    # Subtest: Test Suite \#4
        # Subtest: Test \#1
        ok 1 - Test \#1
          ---
          duration_ms: 0.3393
          ...
        # Subtest: Test \#2
        ok 2 - Test \#2
          ---
          duration_ms: 0.1305
          ...
        1..2
    ok 5 - Test Suite \#4
      ---
      duration_ms: 0.8494
      ...
    1..5
ok 1 - All Tests
  ---
  duration_ms: 8.4926
  ...
1..1
# tests 1
# pass 1
# fail 0
# cancelled 0
# skipped 0
# todo 0
# duration_ms 39.745
```

Ideally, the output I'd like to see, even just using the standard `node --test` run method would be something like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<testsuites name="Test Suites Name">
	<testsuite name="Test Suite #1b" time="0.002064" disabled="0" errors="0" tests="2" failures="0" skipped="0">
		<testcase name="Test #1" time="0.000582" classname="Test Suite #1b" file="testSuite1.js"/>
		<testcase name="Test #2" time="0.000152" classname="Test Suite #1b" file="testSuite1.js"/>
	</testsuite>
	<testsuite name="Test Suite #1a" time="0.000694" disabled="0" errors="0" tests="2" failures="0" skipped="0">
		<testcase name="Test #1" time="0.000179" classname="Test Suite #1a" file="testSuite1.js"/>
		<testcase name="Test #2" time="0.000141" classname="Test Suite #1a" file="testSuite1.js"/>
	</testsuite>
	<testsuite name="Test Suite #2" time="0.001203" disabled="0" errors="0" tests="2" failures="0" skipped="0" file="validation-tests.js">
		<testsuite name="Test Group #1" time="0.000524" disabled="0" errors="0" tests="2" failures="0" skipped="0">
			<testcase name="Test #1" time="0.000201" classname="Test Suite #2/Test Group #1" file="testSuite2.js"/>
			<testcase name="Test #2" time="0.000119" classname="Test Suite #2 - Test Group #1" file="testSuite2.js"/>
		</testsuite>
		<testsuite name="Test Group #2" time="0.000489" disabled="0" errors="0" tests="2" failures="0" skipped="0">
			<testcase name="Test Group #2/Test #1" time="0.000179" classname="Test Suite #2" file="testSuite2.js"/>
			<testcase name="Test Group #2 - Test #2" time="0.000111" classname="Test Suite #2" file="testSuite2.js"/>
		</testsuite>
	</testsuite>
	<testsuite name="Test Suite #3" time="0.000511" disabled="0" errors="0" tests="2" failures="0" skipped="0">
		<testcase name="Test #1" time="0.000146" classname="Test Suite #3" file="testSuite3.js"/>
		<testcase name="Test #2" time="0.000125" classname="Test Suite #3" file="testSuite3.js"/>
	</testsuite>
	<testsuite name="Test Suite #4" time="0.000448" disabled="0" errors="0" tests="2" failures="0" skipped="0">
		<testcase name="Test #1" time="0.000154" classname="Test Suite #4" file="testSuite4.js"/>
		<testcase name="Test #2" time="0.000108" classname="Test Suite #4" file="testSuite4.js"/>
	</testsuite>
</testsuites>

```

That XML, if you're curious, results in what I'd say is almost perfect output in my use case on gitlab:

![image](https://user-images.githubusercontent.com/7980490/229339006-73a8920b-f095-4e5f-aefe-08a704383b84.png)

As you can see, I've not decided whether I prefer tests in a group to have that group listed under 'Test Suites' (eg. using `classname`) or under the suite name (eg. using `name`) or whether I prefer it delimited by `/` or ` - ` - though this isn't too big of a concern at this time really.

I wanted to include the output from gitlab as this is my use-case for `junit` output as gitlab only uses that format for test results; I'm not super familiar with other CI/CD tools to know how they'd interpret/use the `junit` format, though you'd hope it'd be pretty standard across the board, hence using such a format in the first place :)

I know this is a long post, apologies for that, but I wanted to be as clear as I could regarding this.

It seems like the two main problems for me is that the first test suite becomes the root test for some reason when run with `--test` and all 4 test suite files are 'siblings'.. If I group those tests into their own test, it seems to group properly however, though the `TAP` output seems to look fine in both cases unless I'm missing something. This method with them being siblings being from what I can tell, the most standard way to run any tests with `node:test` anyway aside from `run()`.

Aside from that, it'd be great if we can get the filename for each test added to each `<testcase />` node that belongs to that particular file, though I'm not sure if a filename is emitted with the events passed to a test reporter, in my brief test with listening to the events passed to the `TestsStream` I don't recall seeing it but I could've missed it, it's also not present in the `TAP` output so perhaps this would be something to create as an issue/feature request directly for `node:test` itself.

The only time I saw the filename show up was a time I was testing with `node --test` and forgot to remove one of the suites from within an `export` - thus no tests actually ran within that file, so it showed the filename as the `Subtest` name in the `TAP` output but that's not particularly helpful.

Any help you can provide is appreciated; I don't think my use-case is too weird other than the way I've initiated tests sometimes with the `run-tests.js`, however I don't need to do that and I get very similar results with `node --test` which seems to be the more standard method.

Otherwise, I'm just trying to get `junit`-type results that I can stuff into a common CI/CD platform (gitlab) .. Apologies for my lack of familiarity with `junit` as a format or in general and I know that `node:test` is still experimental but it seemed complete enough for some basic tests and I've had pretty good luck so far with it with the main issues I had already having commits to fix them (such as not being able to access the internal reporters when calling the tests with `run()`)

From looking at those commits, actually, it seems like you @MoLow are responsible or at least partially responsible for them; if I could guess it would seem that you're at least partly involved with the work on `node:test` - so firstly, thank you for your work on that and this reporter otherwise and secondly, hopefully my feedback is helpful/insightful - I'm not particularly trying to do anything in a weird or wrong way - I've only this week started playing with `node:test` and had some weird issues at first but was also using an 18.x version and had updated to latest and some of the weirdness went away. I think part of that weirdness was the reason why I started using the `run_tests.js` in the first place, though as I mentioned it's not something I'm stuck on by any means - if I'm going about something the wrong way, please let me know! :)

Cheers and thanks for your time.

**Comment by MoLow** [comment]
can you please add a minimal repro? this is very details, but hard to understand how it can be reproduced

**Comment by ForbiddenEra** [comment]
> can you please add a minimal repro? this is very details, but hard to understand how it can be reproduced

I did, it's there. Literally the first 4 code blocks.........

But TL/DR:

`run-tests.js`:
```javascript
import test from 'node:test';

import testSuite1 from './test/testSuite1.js';
import testSuite2 from './test/testSuite2.js';
import testSuite3 from './test/testSuite3.js';

(async()=>{
	await testSuite1(t);
	await testSuite2(t);
	await testSuite3(t);
})();
```
`test/testSuite3.js`:
```javascript
import test from 'node:test';
import assert from 'node:assert/strict';
export default async() => {
    t.test('Test Suite #3', async(t) => {
        await t.test('Test #1', async(tt) => {});
        await t.test('Test #2', async(tt) => {});
    });
};
```

`test/testSuite2.js`:
```javascript
import test from 'node:test';
import assert from 'node:assert/strict';
export default async() => {
    test('Test Suite #2', async(t) => {
        await t.test('Test Group #1', async(t) => {
            await t.test('Test #1', async(tt) => {});
            await t.test('Test #2', async(tt) => {});
        });
        await t.test('Test Group #2', async(t) => {
            await t.test('Test #1', async(tt) => {});
            await t.test('Test #2', async(tt) => {});
        });
    });
};
```

`test/testSuite1.js`:
```javascript
import test from 'node:test';
import assert from 'node:assert/strict';
export default async() => {
    t.test('Test Suite #1b', async(t) => {
        await t.test('Test #1', async(tt) => {});
        await t.test('Test #2', async(tt) => {});
    });
    t.test('Test Suite #1a', async(t) => {
        await t.test('Test #1', async(tt) => {});
        await t.test('Test #2', async(tt) => {});
    });
};
```

I really don't know how much more clear I could've been ..?

**Comment by MoLow** [comment]
@ForbiddenEra a fix is available on https://www.npmjs.com/package/@reporters/junit, thanks for reporting this issue!

**Comment by ForbiddenEra** [comment]
> @ForbiddenEra a fix is available on https://www.npmjs.com/package/@reporters/junit, thanks for reporting this issue!

Thanks for the quick fix! I'll take a look even if only to compare notes/output - I was initially going to try and fix it and perhaps submit a PR, however your module is 'older'-style CommonJS and even that aside I've never been particularly a fan of not using `class`es.

I made my own junit implementation overnight - https://github.com/Shaped/junit-reporter if you're at all interested in taking a look. I've also made a JSON reporter but I haven't posted it just yet.

When I have a chance I'll test your updated version and let you know if I run into any issues.

Thanks again!

**Comment by ForbiddenEra** [comment]
> > @ForbiddenEra a fix is available on https://www.npmjs.com/package/@reporters/junit, thanks for reporting this issue!
> 
> Thanks for the quick fix! I'll take a look even if only to compare notes/output - I was initially going to try and fix it and perhaps submit a PR, however your module is 'older'-style CommonJS and even that aside I've never been particularly a fan of not using `class`es.
> 
> I made my own junit implementation overnight - https://github.com/Shaped/junit-reporter if you're at all interested in taking a look. I've also made a JSON reporter but I haven't posted it just yet.
> 
> When I have a chance I'll test your updated version and let you know if I run into any issues.
> 
> Thanks again!

If you're at all interested, JSON reporter published: https://github.com/Shaped/json-reporter

TBH I don't even have a use-case for this one, I started my junit XML version by pushing everything into an object and was going to convert it to XML straight from that object/JSON but I decided to do it differently to keep it _sorta_ `streaming`, but perhaps someone may find it useful someday.

I'll probably also make a basic pretty xHTML reporter as well as I could upload that as an artifact with gitlab ci/cd to gitlab pages or something, though chances are that one will rely on some 3rd party modules (eg. `saxon-js` for generating the HTML5/xHTML5 from XSLT with either JSON or XML input, thus these two basic reporters I threw together being a base for that as well) - I didn't want to use 3rd party modules for these basic reporters though, I could've used some sort of XML builder module or a json-to-xml converter module but aside from wanting to avoid extra modules, again, I wanted to at least _slightly_ take advantage of the streaming nature, though the buffer is only flushed on `test:pass` or `test:fail`, I would've liked to also be able to flush on `test:start` but a lot of the data/properties that need to be added are only available on `test:pass`/`test:fail` anyway.

Any comments appreciated :)

A side note that you might be in a position to comment on (and I may perhaps make an issue on nodejs) - I never had the `test:coverage` event fire and I attempted many different ways to run node hoping it would, eg:

`node --experimental-test-coverage tests/run-test.js`
`node --experimental-test-coverage --tests tests/test/testSuite1.js`
`NODE_V8_COVERAGE=coverage node --experimental-test-coverage tests/run-test.js`
`NODE_V8_COVERAGE=coverage node --experimental-test-coverage --tests tests/test/testSuite1.js`
`NODE_V8_COVERAGE=coverage node --tests tests/test/testSuite1.js`

etc.. and I never saw it fire .. again, I know - experimental, but I'd have figured it would fire at least or something..? I do get coverage stats when using a built-in runner and I do see the coverage files appear when `NODE_V8_COVERAGE` is set.

Not a huge deal, just thought maybe you might have some insight; if not I can make an issue on `nodejs/issues` for it.

Next time I'm on (past zztime) I'll check your updated reporter and let you know how it goes.

Thanks again for your quick work, it's appreciated regardless of my own attempts/implementation!

**Comment by ForbiddenEra** [comment]
I thought I'd take a quick peek before I went AFK:

your updated version output:
```xml
<?xml version="1.0" encoding="utf-8"?>
<testsuites>
        <testsuite name="Test Suite #1-A" time="0.003957" disabled="0" errors="0" tests="2" failures="0" skipped="0" hostname="hostname">
                <testsuite name="Test #1-A-1" time="0.002419" disabled="0" errors="0" tests="3" failures="0" skipped="0" hostname="hostname">
                        <testcase name="Test #1-A-1.1" time="0.000727" classname="test"/>
                        <testcase name="Test #1-A-1.2" time="0.000160" classname="test"/>
                        <testcase name="Test #1-A-1.3" time="0.000093" classname="test"/>
                </testsuite>
                <testcase name="Test #1-A-2" time="0.000129" classname="test"/>
        </testsuite>
        <testcase name="Test Suite #1-B" time="0.004753" classname="test" failure="Expected values to be strictly equal:

2 !== 1
">
                <failure type="testCodeFailure" message="Expected values to be strictly equal:

2 !== 1
">
    at TestContext.&lt;anonymous&gt; (file:///home/forbiddenera/pt/upload-validator/tests/test/systemconf-tests.js:27:24)
    at Test.runInAsyncScope (node:async_hooks:203:9)
    ... 4 lines matching cause stack trace ...
    at async startSubtest (node:internal/test_runner/harness:192:3) {
  failureType: 'testCodeFailure',
  cause: AssertionError: Expected values to be strictly equal:

  2 !== 1

      at TestContext.&lt;anonymous&gt; (file:///home/forbiddenera/pt/upload-validator/tests/test/systemconf-tests.js:27:24)
      at Test.runInAsyncScope (node:async_hooks:203:9)
      at Test.run (node:internal/test_runner/test:547:25)
      at Test.processPendingSubtests (node:internal/test_runner/test:300:27)
      at Test.postRun (node:internal/test_runner/test:637:19)
      at Test.run (node:internal/test_runner/test:575:10)
      at async startSubtest (node:internal/test_runner/harness:192:3) {
    generatedMessage: false,
    code: 'ERR_ASSERTION',
    actual: 2,
    expected: 1,
    operator: 'strictEqual'
  },
  code: 'ERR_TEST_FAILURE'
}
                </failure>
        </testcase>
        <testcase name="Test Suite #1-C" time="0.000257" classname="test">
                <skipped type="skipped" message="Test #1-C-1-skip"/>
        </testcase>
        <testcase name="Test Suite #2" time="0.001740" classname="test">
                <skipped type="skipped" message="A previous test failed - skipping Test Suite #2"/>
        </testcase>
</testsuites>
```

Looks mostly good to me; though I wonder about "Test Suite #1-B", "Test Suite #1-C" and "Test Suite #2" not being wrapped in `<testsuite>` nodes? I also wonder about the `failure` attribute on `<testcase>` and `message` attribute on `<failure>` having un-escaped multi-lines..? As I mentioned previously I'm not super familiar with `junit` specifically but in my experience XML doesn't really like having newlines within an attribute.

I'm also curious what your reasoning (maybe a `junit` thing?) as to why you've added the `hostname` attribute. 

It also seems like we're calculating the count of tests/passed/failed slightly differently, your output showing 2 tests for the "Test Suite #1-A" suite/node where mine shows 5. If I had to guess, it seems like on your output that node has two children without counting any sub-children, mine seems to count children though looking closer just now I noticed that the "Test #1-A-2" node also says 5 which isn't correct for that node, though the "Test #1-A-1" node shows 3 tests which seems reasonable as it has 3 <testcase> children - I'll have to look closer and double check my counting but when I was checking the output originally I was comparing the numbers to the output of your previous version and when they seemed to agree I moved on. 

for reference, output from my implementation:

```xml
<?xml version="1.0" encoding="utf-8"?>
<testsuites>
    <testsuite name="Test Suite #1-A" time="0.004873" disabled="0" errors="0" tests="5" failures="0" skipped="0">
        <testsuite name="Test #1-A-1" time="0.003088" disabled="0" errors="0" tests="3" failures="0" skipped="0">
            <testcase name="Test #1-A-1.1" time="0.000907" classname="Test #1-A-1.1" file="./tests/test/systemconf-tests.js">
            </testcase>
            <testcase name="Test #1-A-1.2" time="0.000191" classname="Test #1-A-1.2" file="./tests/test/systemconf-tests.js">
            </testcase>
            <testcase name="Test #1-A-1.3" time="0.000102" classname="Test #1-A-1.3" file="./tests/test/systemconf-tests.js">
            </testcase>
        </testsuite>
        <testsuite name="Test #1-A-2" time="0.004873" disabled="0" errors="0" tests="5" failures="0" skipped="0">
            <testcase name="Test #1-A-2" time="0.000133" classname="Test #1-A-2" file="./tests/test/systemconf-tests.js">
            </testcase>
        </testsuite>
    </testsuite>
    <testsuite name="Test Suite #1-B" time="0.004706" disabled="0" errors="0" tests="0" failures="1" skipped="0">
        <testcase name="Test Suite #1-B" time="0.004706" classname="Test Suite #1-B" file="./tests/test/systemconf-tests.js">
            <failure type="AssertionError" message="Expected values to be strictly equal:  2 !== 1">
                    at TestContext.<anonymous> (file:///tests/test/systemconf-tests.js:27:24)
    at Test.runInAsyncScope (node:async_hooks:203:9)
    at Test.run (node:internal/test_runner/test:547:25)
    at Test.processPendingSubtests (node:internal/test_runner/test:300:27)
    at Test.postRun (node:internal/test_runner/test:637:19)
    at Test.run (node:internal/test_runner/test:575:10)
    at async startSubtest (node:internal/test_runner/harness:192:3)
            </failure>
        </testcase>
    </testsuite>
    <testsuite name="Test Suite #1-C" time="0.000302" disabled="0" errors="0" tests="0" failures="0" skipped="1">
        <skipped type="skipped" message="Test #1-C-1-skip" />
    </testsuite>
    <testsuite name="Test Suite #2" time="0.002148" disabled="0" errors="0" tests="0" failures="0" skipped="1">
        <skipped type="skipped" message="A previous test failed - skipping Test Suite #2" />
    </testsuite>
</testsuites>
```
